# Generated by Django 4.2.21 on 2025-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
