# Generated by Django 4.2.21 on 2025-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time_in_hours', models.PositiveIntegerField(default=24)),
                ('allow_mother_reschedule', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
