# Generated by Django 4.2.21 on 2025-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
