# Generated by Django 4.2.21 on 2025-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_systemsettings_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], help_text="Only applies if role is 'provider'", max_length=20, null=True),
        ),
    ]
