# Generated by Django 4.2.21 on 2025-08-17 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('genotype', models.CharField(blank=True, max_length=4)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('gravidity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lmp', models.DateField(blank=True, null=True)),
                ('edd', models.DateField(blank=True, null=True)),
                ('medications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother', models.OneToOneField(limit_choices_to={'is_active': True, 'role': 'mother'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gestational_age_weeks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fundal_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fetal_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('urine_protein', models.CharField(blank=True, max_length=10)),
                ('urine_glucose', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'mother'}, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-visit_date', '-id'),
            },
        ),
    ]
