# Generated by Django 4.2.21 on 2025-08-17 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_patienthealthrecord_examinationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationrecord',
            name='admission_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='delivery_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='lie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='oedema',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='presentation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='examinationrecord',
            name='problem_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='blood_group_father',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='haemoglobin_28w',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='haemoglobin_36w',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='haemoglobin_booking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='hepatitis_b_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='infertility_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('treated', 'Treated'), ('untreated', 'Untreated')], max_length=10),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='pap_smear_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='pap_smear_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='previous_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='previous_surgery',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='recent_family_planning_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='rhesus_factor_father',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='rhesus_factor_mother',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='rv_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='ultrasound1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='ultrasound1_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='ultrasound2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='ultrasound2_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='vdrl_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PreviousPregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('gestation_at_delivery', models.CharField(blank=True, max_length=50)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=50)),
                ('labour_duration', models.CharField(blank=True, max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complications', models.TextField(blank=True)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_pregnancies', to='accounts.patienthealthrecord')),
            ],
        ),
    ]
