# Generated by Django 4.2.21 on 2025-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_examinationrecord_admission_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouspregnancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
