# Generated by Django 4.2.21 on 2025-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_notification_appointmentreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
